name: print

on:
  schedule:
   - cron: "0 0 * * SUN" 
  workflow_dispatch:
jobs:
  print-job:
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: echo "Hello, World!"

      - name: Run a scheduled script
        run: echo "Scheduled job ran at $(date -u)"